id = "aleo"
name = "Aleo"
version = "0.0.1"
schema_version = 1
authors = ["MagicGordon"]
description = "Aleo language support for Zed."
repository = "https://github.com/MagicGordon/zed-aleo-extension"

[grammars.aleo]
repository = "https://github.com/MagicGordon/tree-sitter-aleo"
rev = "3bf5e17e4e67c207b5a6138277bad90b83bc901d"

[grammars.leo]
repository = "https://github.com/MagicGordon/tree-sitter-leo"
rev = "8fa404c9f45246b47e4ad88a2fe3d03c65e1a594"
