name = "Leo"
grammar = "leo"
path_suffixes = ["leo"]
line_comments = ["// "]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
]
